# Generated by Django 4.2.13 on 2024-06-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('can_fly', models.BooleanField(default=False)),
                ('symbol', models.CharField(max_length=100)),
                ('sound', models.CharField(max_length=100)),
            ],
        ),
    ]
